# Generated by Django 4.0.1 on 2022-05-06 13:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_alter_persons_phone'),
        ('store', '0001_initial'),
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('logo', models.ImageField(upload_to='uploads/bank_logo/')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('1', 'Check'), ('2', 'Installment')], default=1, max_length=1)),
                ('check_number', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.IntegerField()),
                ('create_time', models.DateTimeField(default=datetime.datetime.now)),
                ('last_edite_time', models.DateTimeField(blank=True, null=True)),
                ('Passed', models.BooleanField(default=False)),
                ('Passed_time', models.DateTimeField(blank=True, null=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transaction.banklist')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='persons.persons')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.stors')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.transactions')),
            ],
        ),
    ]
